## 4.2 NLP(ish)

https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html

## décider de comment on découpe
- sentence ?
- paragraphe (existe pas ici) -> mais possible avec wtpsplit : https://github.com/segment-any-text/wtpsplit
- dire que tant pis ? Ok si utilise modèle avec fenetre suffisante (qwen ? https://huggingface.co/Qwen/Qwen3-Embedding-0.6B)
- faire un check global du nb token par intervention et cut que ce qui dépasse ?
- Passer à l'échelle de la phrase pour tout ce qui va être pour sentiment, réseau de mots, proba des termes, etc.
- etc.

In [ ]:
# TODO: remplacer texte_clean par texte (corrigé dans nb3)
# TODO: aviser si vire id_orateur et utiliser id_acteur partout

# TODO: remove unused imports when finalized
import pandas as pd
import spacy
# import nltk
# from nltk.corpus import stopwords

# import bertopic
from bertopic import BERTopic

# from bertopic.vectorizers import ClassTfidfTransformer
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

# %pip install einops
# !python -m spacy download fr_core_news_sm

In [2]:
df = pd.read_csv(
    "../data/interim/df_repu.csv", low_memory=False, dtype={"ID_orateur": str}
)

In [3]:
df["DateSeance_ts"] = pd.to_datetime(df["DateSeance"], format="%Y%m%d%H%M%S%f")
df["DateSeance_day"] = df["DateSeance_ts"].dt.normalize()  # guess it works

## Bert things

In [4]:
#########
# Si besoin, revenir au plus simple :
#########

# nltk.download("stopwords")
# french_stopwords = list(set(stopwords.words("french")))
# vectorizer_model = CountVectorizer(stop_words=french_stopwords)
# topic_model = bertopic.BERTopic(language="french", vectorizer_model=vectorizer_model)
# # topics, probs = topic_model.fit_transform(df["Texte_clean"])

In [5]:
# TODO: redo with the good sentencetransformer

Stopwords :
- https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#document-length
- Instead, we can use the CountVectorizer to preprocess our documents after having generated embeddings and clustered our documents. Personally, I have found almost no disadvantages to using the CountVectorizer to remove stopwords and it is something I would strongly advise to try out:
- We can also use the ClassTfidfTransformer to reduce the impact of frequent words. The end result is very similar to explicitly removing stopwords but this process does this automatically:

In [ ]:
# TODO: Tester Flaubert et autres, qwen, etc. ALibaba = cry in GPU, , etc. Aviser dans colab ou humanum ?
# Qwen pour sa Context Length ? + est multilingue ?
# pousser vers leur 4B ou 8B si ressources suffisantes ?
# ou https://huggingface.co/jinaai/jina-embeddings-v3

# "dangvantuan/sentence-camembert-large"
# "all-MiniLM-L6-v2"
# Maybe https://huggingface.co/jinaai/jina-embeddings-v3

# embedding_model = SentenceTransformer("jinaai/jina-embeddings-v3", trust_remote_code=True)

#######
# ICI
#######
# Les tests à l'arrache active tigger donnent des trucs pas mal avec
# "Alibaba-NLP/gte-multilingual-base"
# https://huggingface.co/Alibaba-NLP/gte-multilingual-base

In [ ]:
# vectorizer_model et french stopwords
# Avec spacy
nlp = spacy.load("fr_core_news_sm")  # !python -m spacy download fr_core_news_sm
french_stopwords = list(nlp.Defaults.stop_words)
vectorizer_model = CountVectorizer(stop_words=french_stopwords)

# # Ou avec nltk
# import nltk
# from nltk.corpus import stopwords
# nltk.download("stopwords")
# french_stopwords = list(set(stopwords.words("french")))
# vectorizer_model = CountVectorizer(stop_words=french_stopwords)


#####################################
# TODO: Choisir le modèle d'embedding final
#####################################


embedding_model = SentenceTransformer(
    # "Alibaba-NLP/gte-multilingual-base", # cry in gpu, something wrong ?
    # "dangvantuan/sentence-camembert-large",
    "all-MiniLM-L6-v2",  # celui par défaut ?
    # "jinaai/jina-embeddings-v3",
    trust_remote_code=True,
)

print(
    "device used :", embedding_model.device
)  # Vérifie si le modèle est sur GPU ou CPU

# ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

# créer le modèle
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,  # remove stopwords after embbedings
    # ctfidf_model=ctfidf_model, # (or) reduce the impact of frequent word
)

device used : mps:0

In [9]:
# Fiter le modèle
topics, probs = topic_model.fit_transform(
    df["Texte_clean"]
)  # .tolist() ? pas obligatoire ?

# Test taille batch

In [10]:
# Reste quand même trop gros, faudrait couper les interventions sans doute.

# # from sentence_transformers import SentenceTransformer
# import numpy as np

# # embedding_model = SentenceTransformer("jinaai/jina-embeddings-v3", trust_remote_code=True)
# texts = df["Texte_clean"].tolist()

# batch_size = 8
# embeddings = []

# for i in range(0, len(texts), batch_size):
#     batch_texts = texts[i:i+batch_size]
#     batch_embeds = embedding_model.encode(batch_texts, show_progress_bar=False)
#     embeddings.append(batch_embeds)

# embeddings = np.vstack(embeddings)

# topics, probs = topic_model.fit_transform(df["Texte_clean"], embeddings=embeddings)

In [11]:
# # V1 safetensors
# topic_model.save(
#     "../models/bert/camembert_safetensors",
#     serialization="safetensors",
#     save_ctfidf=True,
#     save_embedding_model=embedding_model,
# )

# # V2 pytorch
# topic_model.save(
#     "../models/bert/camembert_pytorch",
#     serialization="pytorch",
#     save_ctfidf=True,
#     save_embedding_model=embedding_model,
# )

# # V3 pickle (pas recommandé ?)
# topic_model.save("../models/bert/############", save_embedding_model=True)

In [12]:
# Load from directory
# loaded_model = BERTopic.load("../models/bert/############")

In [13]:
# TODO: does mean pooling thing really works ?

Pour "dangvantuan/sentence-camembert-large"
- No sentence-transformers model found with name dangvantuan/sentence-camembert-large. Creating a new one with MEAN pooling.
- https://github.com/UKPLab/sentence-transformers/issues/2779 In short: even with a will create a new model with mean pooling warning, your model uses the tokenizer from https://huggingface.co/dangvantuan/sentence-camembert-large.


DOES IT REALLY WORKS ?

In [14]:
# help(topic_model)

In [15]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7026,-1_qu_république_loi_été,"[qu, république, loi, été, bien, faire, état, ...","[Monsieur le président, monsieur le président ..."
1,0,605,0_euros_milliards_budget_finances,"[euros, milliards, budget, finances, millions,...","[Monsieur le président, monsieur le ministre d..."
2,1,412,1_territoires_communes_territoriale_collectivités,"[territoires, communes, territoriale, collecti...","[Monsieur le président, monsieur le secrétaire..."
3,2,370,2_république_ve_vive_exemplaire,"[république, ve, vive, exemplaire, êtes, vie, ...","[La République, c'est lui !, « La République, ..."
4,3,317,3_associations_engagement_contrat_association,"[associations, engagement, contrat, associatio...",[On aurait pu penser que les arguments allaien...
...,...,...,...,...,...
85,84,12,84_caméras_images_piétons_police,"[caméras, images, piétons, police, policiers, ...",[Avant de souligner les interrogations que sus...
86,85,12,85_laïcité_laïque_spirituelles_liberté,"[laïcité, laïque, spirituelles, liberté, croir...","[Tout d'abord, je tiens à rappeler que nous pa..."
87,86,11,86_islamiste_paty_samuel_islamisme,"[islamiste, paty, samuel, islamisme, islamiste...",[Après l'horreur de la décapitation du profess...
88,87,10,87_réservistes_salaire_enseignants_logements,"[réservistes, salaire, enseignants, logements,...","[Non.Pour réunir les fonds, ils doivent cherch..."
89,88,10,88_élections_électoral_liste_calédonie,"[élections, électoral, liste, calédonie, corps...",[Je souhaite évoquer l'évolution de la définit...

### Tester des trucs rapides

In [16]:
# # Les principales fonctions à tester pour avoir un aperçu simple :

# topic_model.get_topic_info()
# topic_model.visualize_barchart()
# topic_model.visualize_topics()
# topic_model.visualize_hierarchy()
# topic_model.visualize_documents(df["Texte_clean"].to_list())

### Tester plus

In [17]:
# Optional: visualize
fig_topic_distance_map = topic_model.visualize_topics()
fig_topic_distance_map

In [ ]:
fig_topic_distance_map.write_html("../reports/figures/topic_distance_map.html")

In [18]:
table_topic = topic_model.get_topic_info()
table_topic[:20]

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7026,-1_qu_république_loi_été,"[qu, république, loi, été, bien, faire, état, ...","[Monsieur le président, monsieur le président ..."
1,0,605,0_euros_milliards_budget_finances,"[euros, milliards, budget, finances, millions,...","[Monsieur le président, monsieur le ministre d..."
2,1,412,1_territoires_communes_territoriale_collectivités,"[territoires, communes, territoriale, collecti...","[Monsieur le président, monsieur le secrétaire..."
3,2,370,2_république_ve_vive_exemplaire,"[république, ve, vive, exemplaire, êtes, vie, ...","[La République, c'est lui !, « La République, ..."
4,3,317,3_associations_engagement_contrat_association,"[associations, engagement, contrat, associatio...",[On aurait pu penser que les arguments allaien...
5,4,288,4_violences_violence_ordre_forces,"[violences, violence, ordre, forces, policiers...","[Monsieur le président, monsieur le vice-prési..."
6,5,241,5_constitution_amendement_article_constitutionnel,"[constitution, amendement, article, constituti...",[Nos collègues du groupe Les Républicains prop...
7,6,231,6_républicain_républicains_républicaine_arc,"[républicain, républicains, républicaine, arc,...","[Ce n'est pas républicain !, Voilà un républic..."
8,7,222,7_police_sécurité_gendarmerie_policiers,"[police, sécurité, gendarmerie, policiers, for...","[Monsieur le président, monsieur le ministre, ..."
9,8,216,8_enfants_enfant_parents_instruction,"[enfants, enfant, parents, instruction, famill...","[Madame la présidente, monsieur le ministre, m..."
10,9,202,9_sommes_qu_avez_texte,"[sommes, qu, avez, texte, aujourd, république,...","[Nos travaux sont nourris d'échanges, de lectu..."
11,10,152,10_école_élèves_éducation_classes,"[école, élèves, éducation, classes, écoles, en...","[Depuis 2017, le Gouvernement a placé l'éducat..."
12,11,144,11_liberté_droit_droits_libertés,"[liberté, droit, droits, libertés, homme, mani...","[Le militantisme en lui-même, au sens de cet i..."
13,12,129,12_ministre_monsieur_madame_république,"[ministre, monsieur, madame, république, ve, m...","[Madame la présidente, madame la ministre, mon..."
14,13,124,13_ministre_président_monsieur_qu,"[ministre, président, monsieur, qu, république...","[Monsieur le président du Congrès, monsieur le..."
15,14,119,14_femmes_violences_hommes_sexuelles,"[femmes, violences, hommes, sexuelles, égalité...","[Depuis des générations – depuis l'Antiquité, ..."
16,15,115,15_séparatisme_islamisme_islamiste_islam,"[séparatisme, islamisme, islamiste, islam, mus...",[Je partage entièrement votre analyse quant au...
17,16,112,16_justice_judiciaire_tribunaux_magistrats,"[justice, judiciaire, tribunaux, magistrats, j...",[Je tiens à remercier nos collègues du groupe ...
18,17,111,17_sport_sportives_sportifs_sportif,"[sport, sportives, sportifs, sportif, fédérati...","[Oui, le sport est confronté à la radicalisati..."
19,18,110,18_madame_commission_loi_texte,"[madame, commission, loi, texte, monsieur, pré...","[Madame la présidente, monsieur le ministre, m..."

In [103]:
table_topic.to_csv("../data/interim/table_topics.csv", index=False)

In [97]:
df["Topic"] = topics

In [ ]:
import csv

df.to_csv("../data/interim/df_repu_with_topics.csv", index=False, quoting=csv.QUOTE_ALL)

## Dynamic topic model

* `global_tuning`
  * Whether to average the topic representation of a topic at time *t* with its global topic representation
* `evolution_tuning`
  * Whether to average the topic representation of a topic at time *t* with the topic representation of that topic at time *t-1*
* `nr_bins`
  * The number of bins to put our timestamps into. It is computationally inefficient to extract the topics at thousands of different timestamps. Therefore, it is advised to keep this value below 20.

In [22]:
topics_over_time = topic_model.topics_over_time(
    docs=df["Texte_clean"],
    timestamps=df["DateSeance_ts"],
    global_tuning=True,
    evolution_tuning=True,
    nr_bins=20,
)

In [23]:
fig_dynamic_topic = topic_model.visualize_topics_over_time(
    topics_over_time, top_n_topics=10
)
fig_dynamic_topic

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hoverinfo': 'text',
              'hovertext': [<b>Topic 0</b><br>Words: école, enseignement,
                            éducation, enfants, élèves, <b>Topic 0</b><br>Words:
                            école, élèves, éducation, enseignement, enfants,
                            <b>Topic 0</b><br>Words: école, éducation, élèves,
                            enfants, écoles, <b>Topic 0</b><br>Words: école,
                            élèves, enfants, éducation, handicap, <b>Topic
                            0</b><br>Words: école, enfants, élèves, éducation,
                            enseignement, <b>Topic 0</b><br>Words: école, enfants,
                            éducation, enfance, jeunes, <b>Topic 0</b><br>Words:
                            école, élèves, enfants, éducation, enseignement,
                            <b>Topic 0</b><br>Words: handicap, école, élèves,
                            enfants, éducation, <b>Topic 0</b><br>Words: école,
                            enfants, directeurs, élèves, parents, <b>Topic
                            0</b><br>Words: école, éducation, élèves, enfants,
                            enseignants, <b>Topic 0</b><br>Words: école, enfants,
                            instruction, éducation, famille, <b>Topic
                            0</b><br>Words: enfants, école, enfant, instruction,
                            famille, <b>Topic 0</b><br>Words: école, élèves,
                            directeurs, éducation, enseignement, <b>Topic
                            0</b><br>Words: école, enfants, élèves, éducation,
                            scolaire, <b>Topic 0</b><br>Words: école, handicap,
                            élèves, enfants, rentrée, <b>Topic 0</b><br>Words:
                            école, élèves, éducation, scolaire, uniforme, <b>Topic
                            0</b><br>Words: élèves, école, éducation, enfants,
                            enseignants, <b>Topic 0</b><br>Words: école, ensa, opp,
                            handicap, élèves, <b>Topic 0</b><br>Words: école,
                            élèves, parents, éducation, enfants, <b>Topic
                            0</b><br>Words: école, élèves, enfants, éducation,
                            enseignement],
              'marker': {'color': '#E69F00'},
              'mode': 'lines',
              'name': '0_école_élèves_enfants_éducation',
              'type': 'scatter',
              'x': array(['2017-06-26T02:08:09.600000000', '2017-11-02T10:12:00.000000000',
                          '2018-03-09T05:24:00.000000000', '2018-07-14T00:36:00.000000000',
                          '2018-11-17T19:48:00.000000000', '2019-03-24T15:00:00.000000000',
                          '2019-07-29T10:12:00.000000000', '2019-12-03T05:24:00.000000000',
                          '2020-04-08T00:36:00.000000000', '2020-08-12T19:48:00.000000000',
                          '2020-12-17T15:00:00.000000000', '2021-04-23T10:12:00.000000000',
                          '2021-08-28T05:24:00.000000000', '2022-01-02T00:36:00.000000000',
                          '2022-05-08T19:48:00.000000000', '2022-09-12T15:00:00.000000000',
                          '2023-01-17T10:12:00.000000000', '2023-05-24T05:24:00.000000000',
                          '2023-09-28T00:36:00.000000000', '2024-02-01T19:48:00.000000000'],
                         dtype='datetime64[ns]'),
              'y': {'bdata': 'CAA6AEUAHQCkACMAIgAUACAAJgC8ADkAKgATAAsAVAAyABQAaABGAA==', 'dtype': 'i2'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 1</b><br>Words: euros, impôt, budget,
                            milliards, millions, <b>Topic 1</b><br>Words: euros,
                            milliards, finances, impôt, budget, <b>Topic
                            1</b><br>Words: euros, finances, budgétaire, milliards,
                            budget, <b>Topic 1</b><br>Words: euros, budget,
                            finances, milliards, millions, <b>Topic 1</b><br>Words:
                            euros, milliards, finances, impôt, budget, <b>Topic
                            1</b><br>Words: euros, impôt, milliards, budget, taxe,
                            <b>Topic 1</b><br>Words: euros, budget, crédits,
                            milliards, millions, <b>Topic 1</b><br>Words: retraite,
                            euros, réforme, pensions, système, <b>Topic
                            1</b><br>Words: finances, euros, milliards, dette,
                            budget, <b>Topic 1</b><br>Words: euros, millions,
                            budget, crédits, recherche, <b>Topic 1</b><br>Words:
                            euros, héritage, fiscalité, marielle, sarnez, <b>Topic
                            1</b><br>Words: évaluation, euros, finances, milliards,
                            chômage, <b>Topic 1</b><br>Words: euros, milliards,
                            crédits, budget, 2022, <b>Topic 1</b><br>Words: frais,
                            réseau, bancaires, euros, travailleurs, <b>Topic
                            1</b><br>Words: salariés, euros, milliards, finances,
                            prime, <b>Topic 1</b><br>Words: finances, euros,
                            milliards, budget, collectivités, <b>Topic
                            1</b><br>Words: euros, milliards, lpm, armées, armée,
                            <b>Topic 1</b><br>Words: milliards, euros, inflation,
                            locataires, finances, <b>Topic 1</b><br>Words: budget,
                            euros, milliards, finances, inflation, <b>Topic
                            1</b><br>Words: milliards, euros, économies,
                            entreprises, budget],
              'marker': {'color': '#56B4E9'},
              'mode': 'lines',
              'name': '1_euros_milliards_budget_finances',
              'type': 'scatter',
              'x': array(['2017-06-26T02:08:09.600000000', '2017-11-02T10:12:00.000000000',
                          '2018-03-09T05:24:00.000000000', '2018-07-14T00:36:00.000000000',
                          '2018-11-17T19:48:00.000000000', '2019-03-24T15:00:00.000000000',
                          '2019-07-29T10:12:00.000000000', '2019-12-03T05:24:00.000000000',
                          '2020-04-08T00:36:00.000000000', '2020-08-12T19:48:00.000000000',
                          '2020-12-17T15:00:00.000000000', '2021-04-23T10:12:00.000000000',
                          '2021-08-28T05:24:00.000000000', '2022-01-02T00:36:00.000000000',
                          '2022-05-08T19:48:00.000000000', '2022-09-12T15:00:00.000000000',
                          '2023-01-17T10:12:00.000000000', '2023-05-24T05:24:00.000000000',
                          '2023-09-28T00:36:00.000000000', '2024-02-01T19:48:00.000000000'],
                         dtype='datetime64[ns]'),
              'y': {'bdata': 'MDIXPCwoLxIaJBAOKAcUNB4bKQ8=', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 2</b><br>Words: république, chargeait,
                            indigènes, traduites, cadeau, <b>Topic 2</b><br>Words:
                            république, esquissée, faillite, contractuelle,
                            extrémistes, <b>Topic 2</b><br>Words: république, pasà,
                            ve, acte, intolérable, <b>Topic 2</b><br>Words:
                            république, exemplaire, vive, sitôt, barbouzes,
                            <b>Topic 2</b><br>Words: république, ve, vive, bâtit,
                            fusibles, <b>Topic 2</b><br>Words: république, honoré,
                            tontons, flingueurs, fusibles, <b>Topic 2</b><br>Words:
                            république, guillemets, césar, virtuelle, romaine,
                            <b>Topic 2</b><br>Words: république, ve, excuse,
                            chiffonne, vantent, <b>Topic 2</b><br>Words:
                            république, fromage, bousculés, délirant, sourd,
                            <b>Topic 2</b><br>Words: république, viie, drame,
                            zecler, réactionnaire, <b>Topic 2</b><br>Words:
                            république, ve, vive, abad, support, <b>Topic
                            2</b><br>Words: république, changerions, danser,
                            négocie, défient, <b>Topic 2</b><br>Words: république,
                            chambre, laïque, hein, opérette, <b>Topic
                            2</b><br>Words: république, martel, disloquée, êtes,
                            geôles, <b>Topic 2</b><br>Words: vive, république,
                            taisez, censeurs, premiers, <b>Topic 2</b><br>Words:
                            république, ve, vie, unanimistes, supportez, <b>Topic
                            2</b><br>Words: république, respectez, aimez, vive,
                            césar, <b>Topic 2</b><br>Words: république, saccagez,
                            ve, mauvaise, marge, <b>Topic 2</b><br>Words:
                            république, vive, cédé, ve, parlez, <b>Topic
                            2</b><br>Words: république, vive, rafah, rpcr, attaque],
              'marker': {'color': '#009E73'},
              'mode': 'lines',
              'name': '2_république_vive_ve_exemplaire',
              'type': 'scatter',
              'x': array(['2017-06-26T02:08:09.600000000', '2017-11-02T10:12:00.000000000',
                          '2018-03-09T05:24:00.000000000', '2018-07-14T00:36:00.000000000',
                          '2018-11-17T19:48:00.000000000', '2019-03-24T15:00:00.000000000',
                          '2019-07-29T10:12:00.000000000', '2019-12-03T05:24:00.000000000',
                          '2020-04-08T00:36:00.000000000', '2020-08-12T19:48:00.000000000',
                          '2020-12-17T15:00:00.000000000', '2021-04-23T10:12:00.000000000',
                          '2021-08-28T05:24:00.000000000', '2022-01-02T00:36:00.000000000',
                          '2022-05-08T19:48:00.000000000', '2022-09-12T15:00:00.000000000',
                          '2023-01-17T10:12:00.000000000', '2023-05-24T05:24:00.000000000',
                          '2023-09-28T00:36:00.000000000', '2024-02-01T19:48:00.000000000'],
                         dtype='datetime64[ns]'),
              'y': {'bdata': 'CggZKBIRCRMICh4KCwUHFhsaGxM=', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 3</b><br>Words: amiante, 1997, ouvriers,
                            investigations, danger, <b>Topic 3</b><br>Words:
                            partiel, travail, femmes, précarité, salariales,
                            <b>Topic 3</b><br>Words: violences, violence, ordre,
                            forces, sexuelles, <b>Topic 3</b><br>Words: forces,
                            véhicules, bagages, ordre, sécurité, <b>Topic
                            3</b><br>Words: ordre, violences, manifestations,
                            violence, forces, <b>Topic 3</b><br>Words: police,
                            ordre, forces, policiers, violence, <b>Topic
                            3</b><br>Words: pompiers, sapeurs, agressions,
                            violence, actes, <b>Topic 3</b><br>Words: violences,
                            ordre, forces, violence, manifestations, <b>Topic
                            3</b><br>Words: violences, police, policiers, violence,
                            victimes, <b>Topic 3</b><br>Words: police, policiers,
                            violence, forces, ordre, <b>Topic 3</b><br>Words:
                            violences, élus, police, ordre, violence, <b>Topic
                            3</b><br>Words: policiers, violences, police, forces,
                            foncier, <b>Topic 3</b><br>Words: harkis, camps,
                            violence, réparation, reconnaissance, <b>Topic
                            3</b><br>Words: harkis, ouïghours, violence, violences,
                            ordre, <b>Topic 3</b><br>Words: lyon, martinique,
                            guillotière, drogue, lyonnais, <b>Topic 3</b><br>Words:
                            police, policiers, thau, ordre, forces, <b>Topic
                            3</b><br>Words: violences, violence, extrême, droite,
                            ordre, <b>Topic 3</b><br>Words: violences, policiers,
                            ordre, été, forces, <b>Topic 3</b><br>Words: homicide,
                            violences, familles, victimes, violence, <b>Topic
                            3</b><br>Words: violences, élus, violence, ordre,
                            maire],
              'marker': {'color': '#F0E442'},
              'mode': 'lines',
              'name': '3_violences_violence_ordre_forces',
              'type': 'scatter',
              'x': array(['2017-06-26T02:08:09.600000000', '2017-11-02T10:12:00.000000000',
                          '2018-03-09T05:24:00.000000000', '2018-07-14T00:36:00.000000000',
                          '2018-11-17T19:48:00.000000000', '2019-03-24T15:00:00.000000000',
                          '2019-07-29T10:12:00.000000000', '2019-12-03T05:24:00.000000000',
                          '2020-04-08T00:36:00.000000000', '2020-08-12T19:48:00.000000000',
                          '2020-12-17T15:00:00.000000000', '2021-04-23T10:12:00.000000000',
                          '2021-08-28T05:24:00.000000000', '2022-01-02T00:36:00.000000000',
                          '2022-05-08T19:48:00.000000000', '2022-09-12T15:00:00.000000000',
                          '2023-01-17T10:12:00.000000000', '2023-05-24T05:24:00.000000000',
                          '2023-09-28T00:36:00.000000000', '2024-02-01T19:48:00.000000000'],
                         dtype='datetime64[ns]'),
              'y': {'bdata': 'AwcTBzUOCBEOGxEMCQ0DEiAZEBc=', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 4</b><br>Words: associations, contrat,
                            association, engagement, cultuelles, <b>Topic
                            4</b><br>Words: associations, associatif, engagement,
                            associative, bénévoles, <b>Topic 4</b><br>Words:
                            associations, engagement, associatif, association,
                            cultuelles, <b>Topic 4</b><br>Words: associatif,
                            assouplies, mirallès, patricia, vibrant, <b>Topic
                            4</b><br>Words: digues, durablement, disparition,
                            opposés, assumer, <b>Topic 4</b><br>Words:
                            associations, engagement, associatif, citoyen, contrat,
                            <b>Topic 4</b><br>Words: associations, engagement,
                            associative, fdva, millions, <b>Topic 4</b><br>Words:
                            associations, engagement, attitude, molac, taxe,
                            <b>Topic 4</b><br>Words: associations, associatif,
                            fonds, engagement, millions, <b>Topic 4</b><br>Words:
                            associations, contrat, engagement, association,
                            républicain, <b>Topic 4</b><br>Words: associations,
                            contrat, association, engagement, associatif, <b>Topic
                            4</b><br>Words: associations, rôle, antiracisme,
                            constitueraient, harcèlement, <b>Topic 4</b><br>Words:
                            territoriaux, artistique, concours, dumi, assistants,
                            <b>Topic 4</b><br>Words: association, dissolution,
                            associations, administrative, engagement, <b>Topic
                            4</b><br>Words: associations, contrat, engagement,
                            association, subventions, <b>Topic 4</b><br>Words:
                            souffrez, associations, engagement, rédaction, aiment,
                            <b>Topic 4</b><br>Words: associations, engagement,
                            bénévole, associatif, bénévoles, <b>Topic
                            4</b><br>Words: associations, engagement, associatif,
                            contrat, bénévole],
              'marker': {'color': '#D55E00'},
              'mode': 'lines',
              'name': '4_associations_engagement_contrat_associ...',
              'type': 'scatter',
              'x': array(['2017-06-26T02:08:09.600000000', '2017-11-02T10:12:00.000000000',
                          '2018-03-09T05:24:00.000000000', '2018-07-14T00:36:00.000000000',
                          '2018-11-17T19:48:00.000000000', '2019-03-24T15:00:00.000000000',
                          '2019-07-29T10:12:00.000000000', '2019-12-03T05:24:00.000000000',
                          '2020-08-12T19:48:00.000000000', '2020-12-17T15:00:00.000000000',
                          '2021-04-23T10:12:00.000000000', '2021-08-28T05:24:00.000000000',
                          '2022-01-02T00:36:00.000000000', '2022-09-12T15:00:00.000000000',
                          '2023-01-17T10:12:00.000000000', '2023-05-24T05:24:00.000000000',
                          '2023-09-28T00:36:00.000000000', '2024-02-01T19:48:00.000000000'],
                         dtype='datetime64[ns]'),
              'y': {'bdata': 'BwAEAAgAAgADAAgAAwADAAIAvQAsAAEAAgAEAAwAAwAKAAcA', 'dtype': 'i2'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 5</b><br>Words: police, sécurité, judiciaire,
                            contrôle, mesures, <b>Topic 5</b><br>Words: police,
                            sécurité, forces, contrôles, récépissé, <b>Topic
                            5</b><br>Words: police, sécurité, gendarmerie,
                            quartiers, effectifs, <b>Topic 5</b><br>Words: police,
                            sécurité, policiers, caméras, forces, <b>Topic
                            5</b><br>Words: police, sécurité, roubaix, quartiers,
                            policiers, <b>Topic 5</b><br>Words: police, sécurité,
                            quartiers, sapeurs, pompiers, <b>Topic 5</b><br>Words:
                            police, sécurité, policiers, gendarmes, reconquête,
                            <b>Topic 5</b><br>Words: police, perpignan, vols,
                            sécurité, stupéfiants, <b>Topic 5</b><br>Words: police,
                            sécurité, agents, fresque, républicaine, <b>Topic
                            5</b><br>Words: police, sécurité, municipale,
                            gendarmerie, forces, <b>Topic 5</b><br>Words: police,
                            sécurité, municipale, policiers, forces, <b>Topic
                            5</b><br>Words: police, sécurité, pompiers, sapeurs,
                            policiers, <b>Topic 5</b><br>Words: police, sécurité,
                            pompiers, forces, ordre, <b>Topic 5</b><br>Words:
                            imaginais, crimée, gendarmerie, police, changerez,
                            <b>Topic 5</b><br>Words: police, sécurité, gendarmerie,
                            policiers, brigades, <b>Topic 5</b><br>Words: drones,
                            police, gendarmerie, sécurité, policiers, <b>Topic
                            5</b><br>Words: bravent, police, utilisation,
                            cyberdélits, préfectorales, <b>Topic 5</b><br>Words:
                            police, menton, sécurité, intérieur, paf, <b>Topic
                            5</b><br>Words: clspd, police, obtempérer, tirés,
                            présence],
              'marker': {'color': '#0072B2'},
              'mode': 'lines',
              'name': '5_police_sécurité_gendarmerie_policiers',
              'type': 'scatter',
              'x': array(['2017-06-26T02:08:09.600000000', '2017-11-02T10:12:00.000000000',

In [ ]:
fig_dynamic_topic.write_html("../reports/figures/dynamic_topics.html")

## Hierarchical topics

In [32]:
hierarchical_topics = topic_model.hierarchical_topics(df["Texte_clean"])

100%|██████████| 71/71 [00:00<00:00, 692.89it/s]

In [ ]:
fig_hierarchical = topic_model.visualize_hierarchy(
    hierarchical_topics=hierarchical_topics
)
fig_hierarchical

In [ ]:
fig_hierarchical.write_html("../reports/figures/hierarchical_topics.html")

In [40]:
tree = topic_model.get_topic_tree(hierarchical_topics)
print(tree)

.
├─république_républicain_arc_républicains_honte
│    ├─républicain_arc_républicains_république_grâce
│    │    ├─■──arc_républicain_sortir_étonnement_situerait ── Topic: 58
│    │    └─républicain_républicains_république_grâce_iiie
│    │         ├─■──républicain_république_iiie_ordre_barrage ── Topic: 16
│    │         └─■──républicains_grâce_républicain_attachées_espèrent ── Topic: 40
│    └─république_honte_ve_aimez_vie
│         ├─république_honte_ve_vie_êtes
│         │    ├─■──république_honte_êtes_détruisant_détruisez ── Topic: 20
│         │    └─■──ve_république_vie_présidente_pen ── Topic: 30
│         └─■──aimez_aiment_république_rance_aimait ── Topic: 67
└─qu_république_loi_été_france
     ├─qu_loi_république_france_bien
     │    ├─calédonie_nouvelle_49_ve_république
     │    │    ├─droite_extrême_gauche_peur_histoire
     │    │    │    ├─■──extrême_droite_immigration_peur_ennemi ── Topic: 71
     │    │    │    └─■──droite_extrême_gauche_histoire_dos ── Topic: 39
     │    │    └─calédonie_nouvelle_49_ve_élections
     │    │         ├─49_ve_assemblée_avez_constitution
     │    │         │    ├─retraites_réforme_peuple_avez_démocratie
     │    │         │    │    ├─■──avez_réparerons_démocratie_macron_emmanuel ── Topic: 44
     │    │         │    │    └─■──retraites_réforme_peuple_retraite_64 ── Topic: 31
     │    │         │    └─49_ve_constitution_assemblée_majorité
     │    │         │         ├─■──49_ve_censure_assemblée_majorité ── Topic: 4
     │    │         │         └─■──49_constitution_article_alinéa_1958 ── Topic: 36
     │    │         └─calédonie_nouvelle_élections_scrutin_calédoniens
     │    │              ├─■──scrutin_proportionnelle_mode_majoritaire_ve ── Topic: 22
     │    │              └─■──calédonie_nouvelle_calédoniens_accord_nouméa ── Topic: 12
     │    └─qu_loi_république_france_droit
     │         ├─mer_collectivités_territoires_qu_euros
     │         │    ├─langues_armées_drapeau_langue_militaire
     │         │    │    ├─langues_langue_régionales_sport_française
     │         │    │    │    ├─■──esclavage_mer_toussaint_louverture_aboli ── Topic: 56
     │         │    │    │    └─langues_langue_régionales_sport_jeux
     │         │    │    │         ├─■──langues_langue_régionales_française_enseignement ── Topic: 38
     │         │    │    │         └─■──sport_jeux_sportifs_clubs_sportive ── Topic: 61
     │         │    │    └─armées_drapeau_militaire_défense_programmation
     │         │    │         ├─armées_militaire_défense_lpm_programmation
     │         │    │         │    ├─■──armées_lpm_militaire_programmation_défense ── Topic: 11
     │         │    │         │    └─■──snu_jeunesse_jeunes_militaire_smv ── Topic: 43
     │         │    │         └─■──drapeau_mairies_européen_tricolore_pavoisement ── Topic: 10
     │         │    └─mer_collectivités_territoires_qu_euros
     │         │         ├─collectivités_milliards_finances_euros_dette
     │         │         │    ├─■──impôt_salaires_riches_milliards_entreprises ── Topic: 32
     │         │         │    └─collectivités_milliards_finances_dette_publiques
     │         │         │         ├─dette_milliards_publiques_écologique_finances
     │         │         │         │    ├─■──scientifique_écologique_climatique_énergie_nucléaire ── Topic: 15
     │         │         │         │    └─■──dette_milliards_publiques_dépenses_finances ── Topic: 45
     │         │         │         └─■──collectivités_communes_locales_finances_dgf ── Topic: 14
     │         │         └─mer_territoires_polynésie_ultramarins_ordonnance
     │         │              ├─mer_territoires_polynésie_ultramarins_ordonnance
     │         │              │    ├─mer_territoires_polynésie_ultramarins_ordonnance
     │         │              │    │    ├─mer_territoires_polynésie_ultramarins_ordonnance
     │         │              │    │    │    ├─■──polynésie_ordonnance_française_fonction_publique ── Topic: 27
     │         │              │    │    │    └─■──mer_territoires_ultramarins_prix_eau ── Topic: 6
     │         │              │    │    └─■──logement_logements_locataires_abri_domicile ── Topic: 13
     │         │              │    └─■──agricole_exploitation_agriculteurs_marins_agriculture ── Topic: 42
     │         │              └─services_dématérialisation_publics_numérique_accueil
     │         │                   ├─■──vols_métropoles_serm_transports_ferroviaire ── Topic: 47
     │         │                   └─■──dématérialisation_services_numérique_publics_accueil ── Topic: 64
     │         └─droit_loi_femmes_santé_qu
     │              ├─droit_femmes_santé_loi_qu
     │              │    ├─emploi_salariés_salaires_travail_salaire
     │              │    │    ├─■──promesse_dignité_siècles_précaires_correspondre ── Topic: 68
     │              │    │    └─emploi_salariés_salaires_travail_salaire
     │              │    │         ├─emploi_salariés_salaires_salaire_entreprises
     │              │    │         │    ├─■──emploi_chômage_chômeurs_travail_rsa ── Topic: 34
     │              │    │         │    └─■──salariés_salaire_salaires_entreprises_valeur ── Topic: 24
     │              │    │         └─■──mairie_fonction_secrétaires_publique_métier ── Topic: 65
     │              │    └─droit_santé_loi_qu_femmes
     │              │         ├─santé_droit_loi_étrangers_qu
     │              │         │    ├─santé_soins_hôpital_soignants_système
     │              │         │    │    ├─■──soignants_vaccinés_vaccinale_santé_covid ── Topic: 53
     │              │         │    │    └─■──santé_soins_hôpital_médecins_soignants ── Topic: 5
     │              │         │    └─droit_étrangers_femmes_immigration_asile
     │              │         │         ├─■──sociale_sécurité_constitutionnelle_institution_constitution ── Topic: 26
     │              │         │         └─droit_étrangers_femmes_immigration_asile
     │              │         │              ├─étrangers_immigration_asile_france_intégration
     │              │         │              │    ├─■──texte_remercie_proposition_loi_amendements ── Topic: 17
     │              │         │              │    └─étrangers_immigration_asile_intégration_france
     │              │         │              │         ├─■──république_sommes_valeurs_français_compromis ── Topic: 2
     │              │         │              │         └─■──étrangers_immigration_asile_intégration_expulsion ── Topic: 0
     │              │         │              └─■──femmes_ivg_avortement_droit_liberté ── Topic: 21
     │              │         └─cnil_ligne_numérique_données_libertés
     │              │              ├─■──cnil_drones_données_avis_conseil ── Topic: 41
     │              │              └─■──ligne_numérique_privée_image_contre ── Topic: 63
     │              └─citoyen_droits_déclaration_homme_article
     │                   ├─■──soustraire_religion_origine_prévaloir_lois ── Topic: 70
     │                   └─■──citoyen_droits_homme_déclaration_liberté ── Topic: 59
     └─école_élèves_qu_république_été
          ├─contre_qu_élus_été_république
          │    ├─france_contre_antisémitisme_terrorisme_arménie
          │    │    ├─mayotte_comores_étrangères_ingérences_kazakhstan
          │    │    │    ├─■──mayotte_comores_mahorais_migratoire_comorienne ── Topic: 52
          │    │    │    └─■──ingérences_étrangères_kazakhstan_mayotte_ingérence ── Topic: 66
          │    │    └─antisémitisme_france_contre_arménie_terrorisme
          │    │         ├─arménie_iran_azerbaïdjan_arménien_karabakh
          │    │         │    ├─■──arménie_azerbaïdjan_arménien_karabakh_arméniens ── Topic: 55
          │    │         │    └─■──iran_islamique_iraniennes_iranien_iraniens ── Topic: 62
          │    │         └─antisémitisme_terrorisme_contre_discriminations_france
          │    │              ├─terrorisme_antisémitisme_haine_extrême_contre
          │    │              │    ├─■──paty_samuel_terrorisme_bernard_dominique ── Topic: 25
          │    │              │    └─antisémitisme_terrorisme_extrême_haine_droite
          │    │              │         ├─■──antisémitisme_israël_haine_antisémites_juifs ── Topic: 7
          │    │              │         └─■──extrême_droite_terrorisme_groupuscules_ultradroite ── Topic: 18
          │    │              └─discriminations_discrimination_victimes_histoire_mémoire
          │    │                   ├─discriminations_discrimination_tests_homosexualité_réparation
          │    │                   │    ├─■──discriminations_discrimination_tests_racisme_statistiques ── Topic: 28
          │    │                   │    └─■──homosexualité_réparation_1942_vichy_homosexuelles ── Topic: 49
          │    │                   └─octobre_histoire_mémoire_algérie_1961
          │    │                        ├─■──biens_restitution_spoliés_culturels_restitutions ── Topic: 69
          │    │                        └─■──octobre_algérie_1961_17_victimes ── Topic: 54
          │    └─élus_associations_policiers_justice_violences
          │         ├─associations_engagement_associatif_bénévoles_contrat
          │         │    ├─associations_engagement_associatif_bénévoles_contrat
          │         │    │    ├─■──séparatisme_loi_principes_confortant_radicalisation ── Topic: 57
          │         │    │    └─associations_engagement_associatif_bénévoles_contrat
          │         │    │         ├─■──associations_contrat_engagement_association_subventions ── Topic: 35
          │         │    │         └─■──associations_bénévoles_engagement_associatif_bénévole ── Topic: 37
          │         │    └─quartiers_reconquête_habitants_bâtiments_reconstruction
          │         │         ├─■──quartiers_bâtiments_reconstruction_publics_reconstruire ── Topic: 60
          │         │         └─■──quartiers_reconquête_populaires_habitants_républicaine ── Topic: 50
          │         └─élus_policiers_justice_violences_police
          │              ├─élus_policiers_police_maires_sécurité
          │              │    ├─■──quartier_drogue_trafic_ville_stupéfiants ── Topic: 48
          │              │    └─élus_policiers_maires_police_violences
          │              │         ├─policiers_police_gendarmes_ordre_forces
          │              │         │    ├─■──policiers_ordre_gendarmes_police_forces ── Topic: 8
          │              │         │    └─■──sécurité_police_policiers_gendarmes_ministère ── Topic: 19
          │              │         └─■──élus_maires_maire_locaux_élu ── Topic: 9
          │              └─justice_magistrats_peine_récidive_peines
          │                   ├─peine_peines_récidive_délits_inéligibilité
          │                   │    ├─■──inéligibilité_peine_violences_délits_complémentaire ── Topic: 51
          │                   │    └─■──peines_récidive_peine_planchers_emprisonnement ── Topic: 46
          │                   └─■──justice_magistrats_judiciaire_magistrature_moyens ── Topic: 29
          └─école_élèves_éducation_laïcité_scolaire
               ├─■──aesh_handicap_enfants_école_élèves ── Topic: 23
               └─école_élèves_laïcité_éducation_enseignants
                    ├─école_élèves_laïcité_éducation_enseignants
                    │    ├─■──laïcité_école_élèves_uniforme_religieux ── Topic: 3
                    │    └─■──élèves_école_éducation_enseignants_enseignement ── Topic: 1
                    └─■──parents_école_élèves_conseils_extrême ── Topic: 33

## Topic reduction

In [ ]:
# topics_to_merge = [[X, Y],
#                    [Z, W]]
# topic_model.merge_topics(df["Texte_clean"], topics_to_merge)

In [ ]:
# DONT : # topic_model.reduce_topics(df["Texte_clean"], nr_topics=40) # DONT, IT NUKES THE TOPICS IN MODEL
# # Access updated topics
# topics = topic_model.topics_

2025-07-02 18:46:30,812 - BERTopic - Topic reduction - Reducing number of topics
2025-07-02 18:46:30,813 - BERTopic - Topic reduction - Reduced number of topics from 20 to 20

### Topics per class

In [52]:
df.columns

Index(['UID', 'SeanceRef', 'SessionRef', 'DateSeance', 'DateSeanceJour',
       'NumSeanceJour', 'NumSeance', 'TypeAssemblee', 'Legislature', 'Session',
       'NomFichierJO', 'President', 'Titre_general', 'Sous_titre',
       'Contexte_hierarchique', 'Section_courante', 'Sujet_point',
       'Valeur_ODJ', 'Point_ID', 'Point_type', 'ID_paragraphe', 'Ordre_seance',
       'Code_grammaire', 'Code_style', 'Code_parole', 'Role_debat',
       'Nom_orateur', 'Qualite_orateur', 'ID_orateur', 'stime', 'Texte',
       'Source_extraction', 'len_dirtytext', 'legislatureLast', 'civ', 'nom',
       'prenom', 'villeNaissance', 'naissance', 'age', 'groupe', 'groupeAbrev',
       'departementNom', 'departementCode', 'circo', 'datePriseFonction',
       'job', 'mail', 'twitter', 'facebook', 'website', 'nombreMandats',
       'experienceDepute', 'scoreParticipation',
       'scoreParticipationSpecialite', 'scoreLoyaute', 'scoreMajorite',
       'active', 'dateMaj', 'Texte_clean', 'repu_match_valide',
       'DateSeance_ts', 'DateSeance_day'],
      dtype='object')

In [74]:
df["groupeAbrev"] = df["groupeAbrev"].fillna("gouv_TEMP")

In [ ]:
# ATTENTION, PLANTAIT À CAUSE DES NA
topics_per_class = topic_model.topics_per_class(
    df["Texte_clean"], classes=df["groupeAbrev"]
)

In [ ]:
fig_topics_per_class = topic_model.visualize_topics_per_class(
    topics_per_class, top_n_topics=10
)
fig_topics_per_class

In [ ]:
fig_topics_per_class.write_html("../reports/figures/topics_per_class.html")

In [ ]:
# TODO: revoir regroupement des topics
# TODO: revoir Topic distribution
# TODO: aviser genAI sur le nom des topics ?

In [105]:
df.shape

(3668, 64)

In [106]:
df["Texte_clean"].str.len().describe()

count     3668.000000
mean      1455.530807
std       1701.023067
min         18.000000
25%        409.750000
50%        926.000000
75%       1856.000000
max      20908.000000
Name: Texte_clean, dtype: float64