In [20]:
import pandas as pd
import re

# Charger le df concaténé des deux législatures
df = pd.read_csv(
    "../data/interim/extract_15_16_concat.csv",
    low_memory=False,
    dtype={
        "id_orateur": str  # éviter identification en float avant d'avoir ajouté le "PA"
    },
)

print("Shape du df chargé : ", df.shape)

Shape du df chargé :  (1127838, 29)

Avant exclusion des fichiers doublons / congrès :
Shape du df chargé :  (1128128, 29)
Shape du df après pré-nettoyage et pré-filtrage :  (683680, 32)

In [22]:
# TODO : deduplication par id_syceron seulement,
# pour choper les doublons de cas
# (voir vérif id syceron mais texte différent ?)

s = df["id_syceron"].dropna()
dups = s[s.duplicated(keep=False)].unique()

table_syceron_dups = df.loc[
    df["id_syceron"].isin(dups),
    [
        "uid",
        "session",
        "id_acteur",
        "id_orateur",
        "nom_orateur",
        "dateSeanceJour",
        "id_syceron",
        "texte",
    ],
].sort_values(["id_syceron"])

print("Nombre d'uid concernés :")
print(table_syceron_dups["uid"].nunique())

print("Liste des uid concernés :")
print(table_syceron_dups["uid"].unique())

display(table_syceron_dups)

Nombre d'uid concernés :
367
Liste des uid concernés :
['CRSANR5L15S2017O1N124' 'CRSANR5L15S2017O1N125' 'CRSANR5L15S2017E1N001'
 'CRSANR5L15S2017E1N002' 'CRSANR5L15S2017E1N004' 'CRSANR5L15S2017E1N003'
 'CRSANR5L15S2017E1N005' 'CRSANR5L15S2017E1N006' 'CRSANR5L15S2017E1N007'
 'CRSANR5L15S2017E1N008' 'CRSANR5L15S2017E1N009' 'CRSANR5L15S2017E1N010'
 'CRSANR5L15S2017E1N011' 'CRSANR5L15S2017E1N012' 'CRSANR5L15S2017E1N013'
 'CRSANR5L15S2017E1N014' 'CRSANR5L15S2017E1N015' 'CRSANR5L15S2017E1N016'
 'CRSANR5L15S2017E1N017' 'CRSANR5L15S2017E1N018' 'CRSANR5L15S2017E1N019'
 'CRSANR5L15S2017E1N020' 'CRSANR5L15S2017E1N021' 'CRSANR5L15S2017E1N022'
 'CRSANR5L15S2017E1N023' 'CRSANR5L15S2017E1N024' 'CRSANR5L15S2017E1N025'
 'CRSANR5L15S2017E1N026' 'CRSANR5L15S2017E1N027' 'CRSANR5L15S2017E1N028'
 'CRSANR5L15S2017E1N029' 'CRSANR5L15S2017E1N030' 'CRSANR5L15S2017E1N031'
 'CRSANR5L15S2017E1N032' 'CRSANR5L15S2017E1N033' 'CRSANR5L15S2017E2N001'
 'CRSANR5L15S2017E2N002' 'CRSANR5L15S2017E2N003' 'CRSANR5L15S2017E2N004'
 'CRSANR5L15S2017E2N005' 'CRSANR5L15S2017E2N006' 'CRSANR5L15S2017E2N007'
 'CRSANR5L15S2017E2N008' 'CRSANR5L15S2018O1N002' 'CRSANR5L15S2018O1N003'
 'CRSANR5L15S2018O1N004' 'CRSANR5L15S2018O1N005' 'CRSANR5L15S2018O1N006'
 'CRSANR5L15S2018O1N007' 'CRSANR5L15S2018O1N008' 'CRSANR5L15S2018O1N009'
 'CRSANR5L15S2018O1N010' 'CRSANR5L15S2018O1N011' 'CRSANR5L15S2018O1N012'
 'CRSANR5L15S2018O1N013' 'CRSANR5L15S2018O1N014' 'CRSANR5L15S2018O1N015'
 'CRSANR5L15S2018O1N016' 'CRSANR5L15S2018O1N017' 'CRSANR5L15S2018O1N018'
 'CRSANR5L15S2018O1N019' 'CRSANR5L15S2018O1N020' 'CRSANR5L15S2018O1N021'
 'CRSANR5L15S2018O1N022' 'CRSANR5L15S2018O1N023' 'CRSANR5L15S2018O1N024'
 'CRSANR5L15S2018O1N025' 'CRSANR5L15S2018O1N026' 'CRSANR5L15S2018O1N028'
 'CRSANR5L15S2018O1N027' 'CRSANR5L15S2018O1N029' 'CRSANR5L15S2018O1N030'
 'CRSANR5L15S2018O1N032' 'CRSANR5L15S2018O1N033' 'CRSANR5L15S2018O1N034'
 'CRSANR5L15S2018O1N035' 'CRSANR5L15S2018O1N036' 'CRSANR5L15S2018O1N037'
 'CRSANR5L15S2018O1N039' 'CRSANR5L15S2018O1N038' 'CRSANR5L15S2018O1N040'
 'CRSANR5L15S2018O1N041' 'CRSANR5L15S2018O1N042' 'CRSANR5L15S2018O1N043'
 'CRSANR5L15S2018O1N044' 'CRSANR5L15S2018O1N046' 'CRSANR5L15S2018O1N045'
 'CRSANR5L15S2018O1N047' 'CRSANR5L15S2018O1N048' 'CRSANR5L15S2018O1N049'
 'CRSANR5L15S2018O1N050' 'CRSANR5L15S2018O1N051' 'CRSANR5L15S2018O1N052'
 'CRSANR5L15S2018O1N053' 'CRSANR5L15S2018O1N054' 'CRSANR5L15S2018O1N055'
 'CRSANR5L15S2018O1N056' 'CRSANR5L15S2018O1N057' 'CRSANR5L15S2018O1N058'
 'CRSANR5L15S2018O1N059' 'CRSANR5L15S2018O1N060' 'CRSANR5L15S2018O1N061'
 'CRSANR5L15S2018O1N062' 'CRSANR5L15S2018O1N063' 'CRSANR5L15S2018O1N064'
 'CRSANR5L15S2018O1N065' 'CRSANR5L15S2018O1N066' 'CRSANR5L15S2018O1N067'
 'CRSANR5L15S2018O1N068' 'CRSANR5L15S2018O1N069' 'CRSANR5L15S2018O1N070'
 'CRSANR5L15S2018O1N071' 'CRSANR5L15S2018O1N072' 'CRSANR5L15S2018O1N073'
 'CRSANR5L15S2018O1N074' 'CRSANR5L15S2018O1N075' 'CRSANR5L15S2018O1N076'
 'CRSANR5L15S2018O1N077' 'CRSANR5L15S2018O1N078' 'CRSANR5L15S2018O1N079'
 'CRSANR5L15S2018O1N080' 'CRSANR5L15S2018O1N081' 'CRSANR5L15S2018O1N082'
 'CRSANR5L15S2018O1N083' 'CRSANR5L15S2018O1N084' 'CRSANR5L15S2018O1N085'
 'CRSANR5L15S2018O1N086' 'CRSANR5L15S2018O1N087' 'CRSANR5L15S2018O1N088'
 'CRSANR5L15S2018O1N089' 'CRSANR5L15S2018O1N090' 'CRSANR5L15S2018O1N091'
 'CRSANR5L15S2018O1N092' 'CRSANR5L15S2018O1N093' 'CRSANR5L15S2018O1N094'
 'CRSANR5L15S2018O1N095' 'CRSANR5L15S2018O1N096' 'CRSANR5L15S2018O1N097'
 'CRSANR5L15S2018O1N098' 'CRSANR5L15S2018O1N099' 'CRSANR5L15S2018O1N100'
 'CRSANR5L15S2018O1N101' 'CRSANR5L15S2018O1N102' 'CRSANR5L15S2018O1N103'
 'CRSANR5L15S2018O1N104' 'CRSANR5L15S2018O1N105' 'CRSANR5L15S2018O1N106'
 'CRSANR5L15S2018O1N107' 'CRSANR5L15S2018O1N109' 'CRSANR5L15S2018O1N108'
 'CRSANR5L15S2018O1N110' 'CRSANR5L15S2018O1N111' 'CRSANR5L15S2018O1N112'
 'CRSANR5L15S2018O1N113' 'CRSANR5L15S2018O1N114' 'CRSANR5L15S2018O1N115'
 'CRSANR5L15S2018O1N116' 'CRSANR5L15S2018O1N117' 'CRSANR5L15S2018O1N118'
 'CRSANR5L15S2018O1N119' 'CRSANR5L15S2018O1N120' 'CRSANR5L15S2018O1N121'
 'CRSANR5L15S2018O1N122' 'CRSANR5L15S2018O1N123' 'CRSANR5L15S2018O1N124'
 'CRSANR5L15S2018O1N125' 'CRSANR5L15S2018O1N126' 'CRSANR5L15S2018O1N127'
 'CRSANR5L15S2018O1N128' 'CRSANR5L15S2018O1N130' 'CRSANR5L15S2018O1N129'
 'CRSANR5L15S2018O1N131' 'CRSANR5L15S2018O1N132' 'CRSANR5L15S2018O1N133'
 'CRSANR5L15S2018O1N134' 'CRSANR5L15S2018O1N135' 'CRSANR5L15S2018O1N136'
 'CRSANR5L15S2018O1N137' 'CRSANR5L15S2018O1N138' 'CRSANR5L15S2018O1N139'
 'CRSANR5L15S2018O1N140' 'CRSANR5L15S2018O1N141' 'CRSANR5L15S2018O1N142'
 'CRSANR5L15S2018O1N143' 'CRSANR5L15S2018O1N144' 'CRSANR5L15S2018O1N145'
 'CRSANR5L15S2018O1N146' 'CRSANR5L15S2018O1N147' 'CRSANR5L15S2018O1N148'
 'CRSANR5L15S2018O1N149' 'CRSANR5L15S2018O1N150' 'CRSANR5L15S2018O1N151'
 'CRSANR5L15S2018O1N152' 'CRSANR5L15S2018O1N153' 'CRSANR5L15S2018O1N154'
 'CRSANR5L15S2018O1N155' 'CRSANR5L15S2018O1N156' 'CRSANR5L15S2018O1N157'
 'CRSANR5L15S2018O1N158' 'CRSANR5L15S2018O1N159' 'CRSANR5L15S2018O1N160'
 'CRSANR5L15S2018O1N161' 'CRSANR5L15S2018O1N162' 'CRSANR5L15S2018O1N163'
 'CRSANR5L15S2018O1N164' 'CRSANR5L15S2018O1N165' 'CRSANR5L15S2018O1N166'
 'CRSANR5L15S2018O1N167' 'CRSANR5L15S2018O1N168' 'CRSANR5L15S2018O1N169'
 'CRSANR5L15S2018O1N170' 'CRSANR5L15S2018O1N171' 'CRSANR5L15S2018O1N172'
 'CRSANR5L15S2018O1N173' 'CRSANR5L15S2018O1N174' 'CRSANR5L15S2018O1N175'
 'CRSANR5L15S2018O1N176' 'CRSANR5L15S2018O1N177' 'CRSANR5L15S2018O1N178'
 'CRSANR5L15S2018O1N179' 'CRSANR5L15S2018O1N180' 'CRSANR5L15S2018O1N181'
 'CRSANR5L15S2018O1N182' 'CRSANR5L15S2018O1N183' 'CRSANR5L15S2018O1N184'
 'CRSANR5L15S2018O1N185' 'CRSANR5L15S2018O1N186' 'CRSANR5L15S2018O1N188'
 'CRSANR5L15S2018O1N187' 'CRSANR5L15S2018O1N189' 'CRSANR5L15S2018O1N190'
 'CRSANR5L15S2018O1N191' 'CRSANR5L15S2018O1N192' 'CRSANR5L15S2018O1N193'
 'CRSANR5L15S2018O1N194' 'CRSANR5L15S2018O1N195' 'CRSANR5L15S2018O1N196'
 'CRSANR5L15S2018O1N197' 'CRSANR5L15S2018O1N199' 'CRSANR5L15S2018O1N198'
 'CRSANR5L15S2018O1N200' 'CRSANR5L15S2018O1N201' 'CRSANR5L15S2018O1N202'
 'CRSANR5L15S2018O1N203' 'CRSANR5L15S2018O1N205' 'CRSANR5L15S2018O1N204'
 'CRSANR5L15S2018O1N206' 'CRSANR5L15S2018O1N207' 'CRSANR5L15S2018O1N208'
 'CRSANR5L15S2018O1N210' 'CRSANR5L15S2018O1N209' 'CRSANR5L15S2018O1N211'
 'CRSANR5L15S2018O1N212' 'CRSANR5L15S2018O1N213' 'CRSANR5L15S2018O1N214'
 'CRSANR5L15S2018O1N215' 'CRSANR5L15S2018O1N216' 'CRSANR5L15S2018O1N217'
 'CRSANR5L15S2018O1N218' 'CRSANR5L15S2018O1N219' 'CRSANR5L15S2018O1N220'
 'CRSANR5L15S2018O1N221' 'CRSANR5L15S2018O1N222' 'CRSANR5L15S2018O1N223'
 'CRSANR5L15S2018O1N224' 'CRSANR5L15S2018O1N225' 'CRSANR5L15S2018O1N226'
 'CRSANR5L15S2018O1N227' 'CRSANR5L15S2018O1N228' 'CRSANR5L15S2018O1N229'
 'CRSANR5L15S2018O1N230' 'CRSANR5L15S2018O1N231' 'CRSANR5L15S2018O1N232'
 'CRSANR5L15S2018O1N233' 'CRSANR5L15S2018O1N234' 'CRSANR5L15S2018O1N235'
 'CRSANR5L15S2018O1N236' 'CRSANR5L15S2018O1N237' 'CRSANR5L15S2018O1N238'
 'CRSANR5L15S2018O1N239' 'CRSANR5L15S2018O1N240' 'CRSANR5L15S2018O1N241'
 'CRSANR5L15S2018O1N242' 'CRSANR5L15S2018O1N243' 'CRSANR5L15S2018O1N244'
 'CRSANR5L15S2018O1N245' 'CRSANR5L15S2018O1N246' 'CRSANR5L15S2018O1N247'
 'CRSANR5L15S2018O1N248' 'CRSANR5L15S2018O1N249' 'CRSANR5L15S2018O1N250'
 'CRSANR5L15S2018O1N251' 'CRSANR5L15S2018O1N253' 'CRSANR5L15S2018O1N252'
 'CRSANR5L15S2018O1N254' 'CRSANR5L15S2018O1N255' 'CRSANR5L15S2018O1N256'
 'CRSANR5L15S2018O1N257' 'CRSANR5L15S2018O1N258' 'CRSANR5L15S2018O1N259'
 'CRSANR5L15S2018O1N260' 'CRSANR5L15S2018O1N261' 'CRSANR5L15S2018O1N262'
 'CRSANR5L15S2018O1N263' 'CRSANR5L15S2018O1N264' 'CRSANR5L15S2018O1N265'
 'CRSANR5L15S2018O1N266' 'CRSANR5L15S2018O1N267' 'CRSANR5L15S2018O1N268'
 'CRSANR5L15S2018O1N269' 'CRSANR5L15S2018O1N270' 'CRSANR5L15S2018O1N271'
 'CRSANR5L15S2018O1N272' 'CRSANR5L15S2018O1N273' 'CRSANR5L15S2018O1N274'
 'CRSANR5L15S2018O1N275' 'CRSANR5L15S2018O1N276' 'CRSANR5L15S2018O1N277'
 'CRSANR5L15S2018O1N278' 'CRSANR5L15S2018O1N279' 'CRSANR5L15S2018O1N280'
 'CRSANR5L15S2018O1N281' 'CRSANR5L15S2018O1N283' 'CRSANR5L15S2018O1N282'
 'CRSANR5L15S2018O1N284' 'CRSANR5L15S2018O1N285' 'CRSANR5L15S2018O1N286'
 'CRSANR5L15S2018O1N287' 'CRSANR5L15S2018O1N288' 'CRSANR5L15S2018O1N289'
 'CRSANR5L15S2018E1N001' 'CRSANR5L15S2018E1N002' 'CRSANR5L15S2018E1N003'
 'CRSANR5L15S2018E1N004' 'CRSANR5L15S2018E1N005' 'CRSANR5L15S2018E1N006'
 'CRSANR5L15S2018E1N007' 'CRSANR5L15S2018E1N008' 'CRSANR5L15S2018E1N009'
 'CRSANR5L15S2018E1N010' 'CRSANR5L15S2018E1N011' 'CRSANR5L15S2018E1N012'
 'CRSANR5L15S2018E1N013' 'CRSANR5L15S2018E1N014' 'CRSANR5L15S2018E1N015'
 'CRSANR5L15S2018E1N016' 'CRSANR5L15S2018E1N017' 'CRSANR5L15S2018E1N018'
 'CRSANR5L15S2018E1N019' 'CRSANR5L15S2018E1N020' 'CRSANR5L15S2018E1N021'
 'CRSANR5L15S2018E1N022' 'CRSANR5L15S2018E1N023' 'CRSANR5L15S2018E1N024'
 'CRSANR5L15S2018E1N026' 'CRSANR5L15S2018E1N025' 'CRSANR5L15S2018E1N027'
 'CRSANR5L15S2018E1N028' 'CRSANR5L15S2018E1N029' 'CRSANR5L15S2018E1N030'
 'CRSANR5L15S2018E1N031' 'CRSANR5L15S2018E1N032' 'CRSANR5L15S2018E1N034'
 'CRSANR5L15S2018E1N035' 'CRSANR5L15S2018E1N040' 'CRSANR5L15S2018E1N041'
 'CRSANR5L15S2018E1N044']

,uid,session,id_acteur,id_orateur,nom_orateur,dateSeanceJour,id_syceron,texte
456658,CRSANR5L15S2017O1N124,Session ordinaire 2016-2017,NaN,NaN,NaN,mardi 27 juin 2017,980219,(La séance est levée à \n dix-sept ...
456659,CRSANR5L15S2017O1N124,Session ordinaire 2016-2017,NaN,NaN,NaN,mardi 27 juin 2017,980219,La Directrice du service du compte rendu de la...
428990,CRSANR5L15S2017O1N125,Session ordinaire 2016-2017,NaN,NaN,NaN,mercredi 28 juin 2017,980628,(La séance est levée à zéro heure trente-cinq.)
428991,CRSANR5L15S2017O1N125,Session ordinaire 2016-2017,NaN,NaN,NaN,mercredi 28 juin 2017,980628,La Directrice du service du compte rendu de la...
155060,CRSANR5L15S2017E1N001,Première session extraordinaire 2017,NaN,NaN,NaN,mardi 04 juillet 2017,982060,(La séance est levée à dix-huit heures cinquan...
...,...,...,...,...,...,...,...,...
178367,CRSANR5L15S2018E1N040,Première session extraordinaire 2018,NaN,NaN,NaN,jeudi 26 juillet 2018,1399439,"(La séance est levée, le vendredi 27 juillet 2..."
165500,CRSANR5L15S2018E1N041,Première session extraordinaire 2018,NaN,NaN,NaN,lundi 30 juillet 2018,1400583,Le Directeur du service du compte rendu de la ...
165499,CRSANR5L15S2018E1N041,Première session extraordinaire 2018,NaN,NaN,NaN,lundi 30 juillet 2018,1400583,(La séance est levée à vingt heures quarante-c...
17682,CRSANR5L15S2018E1N044,Première session extraordinaire 2018,NaN,NaN,NaN,mercredi 01 août 2018,1404567,Le Directeur du service du compte rendu de la ...
17681,CRSANR5L15S2018E1N044,Première session extraordinaire 2018,NaN,NaN,NaN,mercredi 01 août 2018,1404567,(La séance est levée à vingt heures quarante.)

In [24]:
# Doublons stricts sur la combinaison id_syceron + texte
tmp_dups = df.loc[
    df["id_syceron"].notna(),
    [
        "uid",
        "id_acteur",
        "id_orateur",
        "nom_orateur",
        "dateSeanceJour",
        "id_syceron",
        "texte",
    ],
].copy()

# # Normalisation légère du texte pour éviter les faux écarts d'espaces
# tmp_dups["texte_norm"] = (
#     tmp_dups["texte"]
#     .fillna("")
#     .astype(str)
#     .str.replace(r"\s+", " ", regex=True)
#     .str.strip()
# )

# restons normal pour l'instant mais avec copie var pour que reste code roule
tmp_dups["texte_norm"] = tmp_dups["texte"]

# Identifier les clés (id_syceron, texte_norm) dupliquées
dups_keys = (
    tmp_dups.groupby(["id_syceron", "texte_norm"], dropna=False)
    .size()
    .reset_index(name="n")
    .query("n > 1")
)

# Table détaillée des lignes concernées
table_syceron_dups = (
    tmp_dups.merge(
        dups_keys[["id_syceron", "texte_norm", "n"]],
        on=["id_syceron", "texte_norm"],
        how="inner",
    )
    .sort_values(["id_syceron", "uid"])
    .drop(columns=["texte_norm"])
)

print("Nb clés dupliquées (id_syceron + texte) :", len(dups_keys))
print("Nb lignes concernées :", len(table_syceron_dups))
display(table_syceron_dups)

Nb clés dupliquées (id_syceron + texte) : 0
Nb lignes concernées : 0

Empty DataFrame
Columns: [uid, id_acteur, id_orateur, nom_orateur, dateSeanceJour, id_syceron, texte, n]
Index: []